/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KKN_TFIDF;

import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.io.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.regex.PatternSyntaxException;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.*;

/**
 *
 * @author zee tech
 */
public class KKN_TFIDF extends javax.swing.JFrame {

    /**
     * Creates new form KKN_TFIDF
     */
    public KKN_TFIDF() {
        initComponents();
    }
    DefaultTableModel model;
        List<List<String>> documents;
    ArrayList<String> edu1, edu2, edu3, edu4, edu5;
    List<String> lEdu1, lEdu2, lEdu3, lEdu4, lEdu5;
    double tfidf, tf, idf, sumTfidf, sumTf;
    String ansTfidf, ansTf, ansIdf;
    FileReader rEdu1, rEdu2, rEdu3, rEdu4, rEdu5;
    String stEdu1, stEdu2, stEdu3, stEdu4, stEdu5;
    String []arrStEdu1, arrStEdu2, arrStEdu3, arrStEdu4, arrStEdu5;    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKknTfidf = new javax.swing.JTable();
        btnDel = new javax.swing.JButton();
        txtQuery = new javax.swing.JTextField();
        btnQuery = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKknTfidf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Return Pos.", "Document", "Sum Tf", "Sum Tfidf"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKknTfidf);

        btnDel.setText("Delete All rows");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnQuery.setText("Query");
        btnQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnQuery)))
                        .addGap(0, 43, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuery))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        for (int i = model.getRowCount() - 1; i >=0 ; i--) {
            model.removeRow(i);
        }
    }//GEN-LAST:event_btnDelActionPerformed
    public void filing() throws Exception{
        //File[] files = new File[10];
        
        rEdu1 = new FileReader("Files/Education/Blog Post of the Day.html"); 
        edu1 = new ArrayList<String>();
        lEdu1 = new ArrayList<String>();
        lEdu1 = (ArrayList<String>) NoHtml.extractText(rEdu1);
        stEdu1 = lEdu1.toString();
        arrStEdu1 = stEdu1.split(" ");
        Collections.addAll(edu1, arrStEdu1);
        
        rEdu2 = new FileReader("Files/Education/Chalkbeat_ Education News for America.html"); 
        edu2 = new ArrayList<String>();
        lEdu2 = new ArrayList<String>();
        lEdu2 = (ArrayList<String>) NoHtml.extractText(rEdu2);
        stEdu2 = lEdu2.toString();
        arrStEdu2 = stEdu2.split(" ");
        Collections.addAll(edu2, arrStEdu2);
        
        rEdu3 = new FileReader("Files/Education/Home _ Edutopia.html"); 
        edu3 = new ArrayList<String>();
        lEdu3 = new ArrayList<String>();
        lEdu3 = (ArrayList<String>) NoHtml.extractText(rEdu3);
        stEdu3 = lEdu3.toString();
        arrStEdu3 = stEdu3.split(" ");
        Collections.addAll(edu3, arrStEdu3);
        
        rEdu4 = new FileReader("Files/Education/Literacy educator, Literacy Professor, Literacy and Reading Blog, Reading Instruction _ Shanahan on Literacy.html"); 
        edu4 = new ArrayList<String>();
        lEdu4 = new ArrayList<String>();
        lEdu4 = (ArrayList<String>) NoHtml.extractText(rEdu4);
        stEdu4 = lEdu4.toString();
        arrStEdu4 = stEdu4.split(" ");
        Collections.addAll(edu4, arrStEdu4);
        
        rEdu5 = new FileReader("Files/Education/Mindshift _ KQED News _ KQED Public Media for Northern CA.html"); 
        edu5 = new ArrayList<String>();
        lEdu5 = new ArrayList<String>();
        lEdu5 = (ArrayList<String>) NoHtml.extractText(rEdu5);
        stEdu5 = lEdu5.toString();
        arrStEdu5 = stEdu5.split(" ");
        Collections.addAll(edu5, arrStEdu5);
        
        documents = Arrays.asList(edu1, edu2, edu3, edu4, edu5);
    }
    public class document{
        int id;
        ArrayList<String> edu;
    }
     public  double sumTfidf(String input){
        Tfidf calculator = new Tfidf();
        tfidf = calculator.tfIdf(edu1, documents, input);
        sumTfidf += tfidf;
        return sumTfidf;
    }
    private double sumTf(String input){
        Tfidf calculator = new Tfidf();
        tf=calculator.tf(edu1, input);
        sumTf += tf;
        return sumTf;
    }
    Scanner s1;
    ArrayList<String> doc;
    String input;
    Iterator<String> iterator;
		
    private void btnQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQueryActionPerformed
        String query = txtQuery.getText();
        s1 = new Scanner(query);
        doc = new ArrayList<String>();
        while (s1.hasNext())
            doc.add(s1.next());
        s1.close();
        try{
            filing();
        }
        catch(Exception e){
            e.printStackTrace();
        }
        for (int i = 0; i < doc.size(); i++) {
            input = doc.get(i);
            Tfidf calculator = new Tfidf();
            tfidf = calculator.tfIdf(edu1, documents, input);
            tf=calculator.tf(edu1, input);
            sumTfidf += tfidf;
            sumTf += tf;
            
        }
            ansTfidf = String.valueOf(sumTfidf);
            ansTf = String.valueOf(sumTf);
            model = (DefaultTableModel) tblKknTfidf.getModel();
            model.addRow(new Object[]{query,"1",ansTf,ansTfidf});
        
            
    }//GEN-LAST:event_btnQueryActionPerformed
public JTable getTblTfidf(){
    return this.tblKknTfidf;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KKN_TFIDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KKN_TFIDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KKN_TFIDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KKN_TFIDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KKN_TFIDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnQuery;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKknTfidf;
    private javax.swing.JTextField txtQuery;
    // End of variables declaration//GEN-END:variables
}
